#!/bin/bash

command=$1
parameter=$2
for obj in ./*; do
	if [ -d "$obj" ]; then
                cd "$obj"
                echo -e "\033[33m $obj \033[0m"
                if [ -z "$parameter" ]
                then
                        git "$command"
                else
                        git "$command" "$parameter"
                fi
                cd ..
                echo
	fi
done